# Final Project

I will implement a Neural Network with Convolutional Layers (a Convolutional Neural Network) to predict the labels of the class’s aggregated Handwritten Digit Data Set.

In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import keras
#import tensorflow as tf 
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Model, Sequential 
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Flatten, Dropout, Dense, Input
from tensorflow.keras.utils import to_categorical
from sklearn.metrics import confusion_matrix
from tensorflow.keras.optimizers import RMSprop 


Part 1.1: Preparing MNIST and the Collected Handwritten Digits for Training



> Load the class’s Handwritten Digit Data Set:



In [ ]:
df = pd.read_csv('combined_digits_1.csv')
digit_x = df[df.columns[0:784]]
digit_y = df[df.columns[784]]



> Process the class’s Handwritten Digit Data Set into 4d tensor



In [ ]:
# data processing
#reshape
digit_x = digit_x.values.reshape((digit_x.shape[0],28,28,1)) 
#print(digit_x.shape)

#normalizing the pixel values
digit_x = digit_x.astype('float32')
digit_x /= 255

#category to 10 classes
digit_y = to_categorical(digit_y)



> Pre-modeling processing



In [ ]:
#loading data
(train_x, train_y), (test_x, test_y) = mnist.load_data()

#mnist data processing
#reshaping data
train_x = train_x.reshape((train_x.shape[0], train_x.shape[1], train_x.shape[2], 1))
test_x = test_x.reshape((test_x.shape[0],test_x.shape[1],test_x.shape[2],1)) 
print(train_x.shape)
print(test_x.shape)

#normalizing the pixel values
train_x = train_x.astype('float32')
test_x = test_x.astype('float32')
train_x /= 255
test_x /= 255

#category to 10 classes
train_y = to_categorical(train_y, 10)
test_y = to_categorical(test_y, 10)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [ ]:
inpx = (28, 28, 1)
inpx = Input(shape=inpx)

layer1 = Conv2D(32, kernel_size=(3, 3), activation='relu')(inpx)
layer2 = MaxPooling2D(pool_size=(3, 3))(layer1)
layer3 = Conv2D(64, (3, 3), activation='relu')(layer2)
layer4 = MaxPooling2D(pool_size=(3, 3))(layer3)
layer5 = Dropout(0.2)(layer4)
layer6 = Flatten()(layer5)
layer7 = Dense(128, activation='sigmoid')(layer6)
layer8 = Dense(10, activation='softmax')(layer7)


Part 1.2: Train and Validate your Model

In [ ]:
model = Model([inpx], layer8)
model.compile(optimizer=RMSprop(),
			loss=keras.losses.categorical_crossentropy,
			metrics=['accuracy'])

model.fit(train_x, train_y, validation_data=(test_x,test_y), epochs=8, batch_size=300)

Epoch 1/8
200/200 [==============================] - 30s 139ms/step - loss: 0.7842 - accuracy: 0.7903 - val_loss: 0.2294 - val_accuracy: 0.9322
Epoch 2/8
200/200 [==============================] - 24s 119ms/step - loss: 0.2186 - accuracy: 0.9349 - val_loss: 0.1210 - val_accuracy: 0.9625
Epoch 3/8
200/200 [==============================] - 23s 115ms/step - loss: 0.1391 - accuracy: 0.9577 - val_loss: 0.0788 - val_accuracy: 0.9764
Epoch 4/8
200/200 [==============================] - 26s 131ms/step - loss: 0.1062 - accuracy: 0.9682 - val_loss: 0.0612 - val_accuracy: 0.9820
Epoch 5/8
200/200 [==============================] - 24s 120ms/step - loss: 0.0866 - accuracy: 0.9738 - val_loss: 0.0548 - val_accuracy: 0.9823
Epoch 6/8
200/200 [==============================] - 23s 115ms/step - loss: 0.0727 - accuracy: 0.9776 - val_loss: 0.0463 - val_accuracy: 0.9858
Epoch 7/8
200/200 [==============================] - 23s 115ms/step - loss: 0.0646 - accuracy: 0.9797 - val_loss: 0.0401 - val_accuracy:

In [ ]:
#evaluting the model on test data
score = model.evaluate(test_x,test_y)
print('accuracy=', score[1])

313/313 [==============================] - 2s 6ms/step - loss: 0.0367 - accuracy: 0.9887
accuracy= 0.9886999726295471


Part 1.3: Test your Model’s Performance

In [ ]:
#model prediction
pred = model.predict(digit_x,max_queue_size = 10)
#convert predictions classes to one hot vectors
y_pred = np.argmax(pred, axis=1)
#convert validation observations to one hot vectors
y_digit = np.argmax(digit_y, axis=1)

#accuracy and confusion matrix
accuracy = np.mean(y_digit == y_pred)
cm = confusion_matrix(y_digit, y_pred)

print('Accuracy: ')
print(accuracy)
print('Confusion Matrix: ')
print(cm)

Accuracy: 
0.6832079021636877
Confusion Matrix: 
[[224  18  12   8   9  33  19  48  14  75]
 [  4 373   7   1   2   4   2  18   0   3]
 [  2  31 278  15   9   5   0  80   0   4]
 [  2  19   8 294   6  12   0  69   1   9]
 [  2  22  17   2 314   7   3  36   1  38]
 [  2  20   5   8   5 346   2  30   2  10]
 [  3  61  16   0  45  48 227  11   9   5]
 [  2  21   1   5   2  10   1 362   0   3]
 [  4  16  27  26   4  25   1  49 231  22]
 [  6  47   0   6  10  14   2  75   9 256]]


Part 1.4: Save Model Object

In [ ]:
model.save("CNN_model.h5")

In [ ]:
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_5 (InputLayer)        [(None, 28, 28, 1)]       0         
                                                                 
 conv2d_8 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d_6 (MaxPooling  (None, 8, 8, 32)         0         
 2D)                                                             
                                                                 
 conv2d_9 (Conv2D)           (None, 6, 6, 64)          18496     
                                                                 
 max_pooling2d_7 (MaxPooling  (None, 2, 2, 64)         0         
 2D)                                                             
                                                                 
 dropout_4 (Dropout)         (None, 2, 2, 64)          0   

In [ ]:
#from tensorflow.keras.models import load_model
model1 = load_model("cnnModel.h5")
